### PR TITLE
Add Rector to members.csv

### PR DESCRIPTION
**Pull request by TomasVotruba**
Hello everyone, 

thanks for amazing initiative :clap:  We're inspired and excited to give back!

Tomas

### CODE REVIEW

**Review by vladh — CHANGES_REQUESTED** [review]
I noticed a few typos in the description — maybe this suggestion is helpful?

> Rector is a PHP tool that you can run on any PHP project to get an instant upgrade or automated refactoring. It gives you safety and lightning speed, and helps you with PHP upgrades, framework upgrades, and improving your code quality. Rector is alive thanks to Open Source projects and the developers behind those projects.

**Comment by vladh** [comment]
Hey @TomasVotruba, thank you for joining, it's great to have you! 🎉 

I had one small suggestion for the JSON file. Otherwise, everything LGTM, and I'll wait for a second review before merging.

**Comment by TomasVotruba** [comment]
@vladh Thanks for quick fix and feedback :+1: 

Your text looks good, so I've update the description:  https://github.com/rectorphp/getrector-com/commit/ede70a2e3578c2c15c9bad27c2a48869bddff3fc

**Review by vladh — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Welcome aboard @TomasVotruba! 🎉

**Comment by TomasVotruba** [comment]
Happy to be here 😊 thanks 🙏

**Pull request merged**
