### PR TITLE
Add Val Town

### PR DESCRIPTION
**Pull request by stevekrouse**
1. We donated the funds!
2. I [wrote the blog post](https://oss.val-town-blog.pages.dev/blog/oss/) and would love your [review on it](https://github.com/val-town/val-town-blog/pull/122) and then will publish. I can publish today or Monday or anytime next week - whenever you get a chance to review - no rush.
3. Here's the endpoint with the data: https://std-oss_pledge.web.val.run and the corresponding val for the curious: https://www.val.town/v/std/oss_pledge
4. That's this PR
5. What sort of branding materials are you looking for? Here's some brand assets for us: https://www.val.town/brand

### CODE REVIEW

**Comment by vladh** [comment]
I love this, so nice to have you on board! 🎉 🎉 🎉

Everything looks perfect to me, but I'll wait for a second reviewer (@chadwhitacre?) before merging this.

**Comment by chadwhitacre** [comment]
Let's goooooo! 🙌 💃 Welcome aboard, @stevekrouse! 😁

**Comment by chadwhitacre** [comment]
Hit an [error](https://github.com/opensourcepledge/osspledge.com/actions/runs/10684777901/job/29616015176), I ended up [replacing](https://github.com/opensourcepledge/osspledge.com/commit/0f9a321192fb0cef8cd19dc5200487be76b8c7a5) the space with a dash in the slug in the csv (as with your GitHub org slug).

**Comment by stevekrouse** [comment]
ah! sorry about that! thanks!

**Comment by chadwhitacre** [comment]
No worries, I noticed it the other day but forgot about it this morning. Anyway we're live now! 🙌

image

**Pull request merged**
