### PR TITLE
feat: add scalar to oss pledge

### PR DESCRIPTION
**Pull request by marclave**
hey hey, couldn't be more stoked to be part of the pledge 🫶 

few things:
1. we published [our blog](https://scalar.com/blog/oss-pledge-2024), would love feedback before we tweet it out/post it on socials :) 
2. [here's our branding](https://drive.google.com/drive/folders/1tllzrRfzZM6kDDY81k_yYqpI5AX5p7pQ?usp=sharing) unless @cameronrohani we got more up to date ones?

im still on recruiting duty and am hopeful to get at least a couple more companies on this list! ✨

### CODE REVIEW

**Review by vladh — APPROVED** [review]

**Review by vladh — CHANGES_REQUESTED** [review]
Would it be possible to have `urlLearnMore` point to something related to Scalar's commitment to Open Source, rather than the home page? If there's no such page, the blog post will do!

(Updated member checklist in #70 to clarify.)

**Comment by vladh** [comment]
Amazing, so nice to have you on board! I just had one small comment.

The post looks great to me, but I'll wait for @chadwhitacre's review before merging.

Looking forward to having you on the website ✨

**Comment by marclave** [comment]
@vladh I updated the `urlLearnMore` link to the blog :)

**Review by vladh — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Woo-hoo! Welcome aboard @marclave! 🥳 💃 

One problem ... the URL logo is bad, I think maybe you meant this:

https://avatars.githubusercontent.com/u/301879?s=200&v=4

Instead of this:

https://github.com/organizations/scalar/settings/profile

Mind updating that in your JSON and we can reimport?

**Comment by chadwhitacre** [comment]
I made https://github.com/scalar/scalar/pull/3032 to fix it upstream. 😁

**Comment by chadwhitacre** [comment]
I tried fixing it locally in c63db494a461e226c7bb81a6ef7136873deb8512 but we refetch on build.

**Comment by chadwhitacre** [comment]
Upstream landed, did some dancing (8d5e5a023aecdf26d327fc8683d86760fc64dc42, f1ee15114198075f5945341037a88a7d553d31c0, a70152dde2d2cd7729fad0acab2940a59340601e) ... we're good! 🙌 

image

**Pull request merged**
