### PR TITLE
Add ndevs column to homepage

### PR DESCRIPTION
**Pull request by chadwhitacre**
For #126.

# Before

image

# After

image

### CODE REVIEW

**Comment by chadwhitacre** [comment]
> What if we move the per dev contribution count into a tooltip or at least de-emphasize it further?

Why? Reasons to leave as-is:

- Shows that there's a range of contributions, emphasizes that $2k is a minimum.
- Not sorted by this column so makes clear that it's not really a competition.
- Matches the /members page, this is a sample of that so draws people in to data exploration (CTA adjusted here as well)

**Comment by chadwhitacre** [comment]
Also this is an incremental change, low-hanging fruit for today. We could do a more significant change but I'd like to bring in @stevenplewis for that.

**Comment by mitsuhiko** [comment]
I'm not a huge fan of showing $/dev given that it's just not a good metric because it does not take into account the size of the company / doesn't work well with large ones.  See also the discussion in #135

So that we are putting it size wise on the same emphasis as the developer count sits wrong with me.

**Comment by chadwhitacre** [comment]
Well currently we are not showing it _at all_ on the homepage and $/dev is all we show, so I think this PR is worth merging even if it ends up being temporary.

**Review by vladh — APPROVED** [review]

**Comment by vladh** [comment]
Will merge this for now, but let's continue the discussion about how to promote members.

**Pull request merged**
