### PR TITLE
Update members.csv to include Emerge Tools

### PR DESCRIPTION
**Pull request by jshchnz**

### CODE REVIEW

**Review by vladh — APPROVED** [review]

**Comment by vladh** [comment]
Love the blog post! 🎉  Will wait for a second review before merging.

**Comment by chadwhitacre** [comment]
Welcome aboard @jshchnz! 💃

**Comment by vladh** [comment]
@jshchnz Could you link us to the Emerge Tools branding materials, preferably with various versions of the logo, so that we can include you on the Nasdaq tower in Times Square?

**Comment by jshchnz** [comment]
Sure thing, how does [this](https://drive.google.com/file/d/1ENx9PRrpWxxpbdvpmVcNva2mDHCrrZls/view?usp=sharing) work?

**Comment by vladh** [comment]
@jshchnz That works perfectly, thanks so much! 🎉

**Pull request merged**
