### PR TITLE
Onboard Sentry

### PR DESCRIPTION
**Pull request by chadwhitacre**

### CODE REVIEW

**Review by vladh — CHANGES_REQUESTED** [review]
@chadwhitacre The JSON file is missing `datetimeModified`, which makes checking for new changes impossible — could we add it?

**Comment by chadwhitacre** [comment]
Ah, I was expecting that we would add that on our side. Wdyt?

**Comment by chadwhitacre** [comment]
Or should we just drop `datetimeModified` entirely? Does it matter? How are we going to use it?

I think my thought in adding it originally is that we could use it to implement a more complex algorithm for fetching JSON files, something like: check `datetimeModified` and if it's recent don't refetch for a month or whatever. That now seems like overcomplication to me and probably we can just drop/ignore it entirely. Eh?

**Comment by chadwhitacre** [comment]
Seeing how we're currently using it:

https://github.com/opensourcepledge/osspledge.com/blob/c6dc6b5e5682019838592006d2980ba6c3520b91/bin/update-member#L38-L42

Since this doesn't save us from the fetch, it seems we could probably just always save the file contents and let git do the work of picking up changes.

**Comment by vladh** [comment]
Cool, let's just assume changed=newer and drop `datetimeModified` entirely, I'll prepare a PR, then I'll merge this!

**Comment by chadwhitacre** [comment]
https://github.com/opensourcepledge/osspledge.com/pull/55 :)

**Comment by vladh** [comment]
That was speedy!

**Comment by vladh** [comment]
Tested and LGTM, merging.

**Comment by vladh** [comment]
We forgot to rename `paymentsToProjects` to `payments`, did that on main in [33a42fc](https://github.com/opensourcepledge/osspledge.com/commit/33a42fce29b4677d0859d7b4ba626a2066ff9e18).

**Comment by vladh** [comment]
Also should have removed `domain`, done in [dcda264](https://github.com/opensourcepledge/osspledge.com/commit/dcda264e4754d058025b6036af30ec9b5940dfca) — it was unused anyway.

**Comment by vladh** [comment]
I also made a few improvements to `deploy.yml` on main.

Deployment done, LGTM! https://osspledge.com/members/sentry/

**Comment by chadwhitacre** [comment]
👍 🎉

**Pull request merged**
