### PR TITLE
Update members.csv: Add Private Packagist

### PR DESCRIPTION
**Pull request by naderman**
Hey, please add us to the list of companies :-)

Blog post here: https://blog.packagist.com/packagist-is-joining-the-open-source-pledge/

### CODE REVIEW

**Comment by vladh** [comment]
So nice to have you on board, @naderman! 🎉 

Everything LGTM, will just wait for a second review.

**Comment by chadwhitacre** [comment]
Welcome aboard! :)

**Comment by naderman** [comment]
@chadwhitacre @vladh realized a bit late that the last step 5 of joining was to provide high res logo:

There are a few variants: logo only as SVG:

vector_logo_with_text
Private Packagist Logo No Text
Private Packagist Logo Horizontal
Private Packagist Logo Horizontal Whitetext

Let me know if you need some other version of this for a different size or background color.

**Comment by naderman** [comment]
Was a bit sad to see our elephant dropped from the logo in black and white, so for future reference here are black/white versions of the logo:

- White with text, horizontal wide
vector_logo_with_text_small_2019_white
- White with text, elephant facing right
vector_logo_with_text_2019_white_right
- White with text, elephant facing left
vector_logo_with_text_2019_white_left

- Black with text, horizontal wide
vector_logo_with_text_small_2019_black
- Black with text, elephant facing right
vector_logo_with_text_2019_black_right
- Black with text, elephant facing left
vector_logo_with_text_2019_black_left

cc @vladh

**Comment by vladh** [comment]
Thank you @naderman, and sorry that we didn't consult with you in more depth about how your logo should be used, that was our mistake.

I'll make sure this is fixed on the website homepage.

**Comment by naderman** [comment]
@vladh No worries hard to coordinate with a deadline, looked cool regardless :-)

**Pull request merged**
