### PR TITLE
Add Chief Tools as member

### PR DESCRIPTION
**Pull request by stayallive**
I might be small still but that doesn't mean I don't believe this is the way!

Small beginnings: https://chief.app/about#osspledge

🎉

### CODE REVIEW

**Review by vladh — APPROVED** [review]

**Comment by vladh** [comment]
Thank you for this! 🎉  Looks good to me, will wait for a second review.

**Comment by chadwhitacre** [comment]
Welcome aboard! :)

**Comment by vladh** [comment]
@stayallive Could you link us to the Chief Tools branding materials, preferably with various versions of the logo, so that we can include you on the Nasdaq tower in Times Square?

**Comment by stayallive** [comment]
Absolutely, let me know if you need or like anything else: [chieftools.zip](https://github.com/user-attachments/files/17102651/chieftools.zip)

**Comment by vladh** [comment]
Thank you @stayallive! :) I'll get back to you if our design team has any special requests.

**Pull request merged**
