### PR TITLE
Remove Sentry SDK

### PR DESCRIPTION
**Pull request by vladh**
I believe the SDK is not currently being used because no DSN etc. is specified, so removing it would be good to reduce file size. I might be wrong, though?

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Okay, we can bring it back later if we want.

**Comment by chadwhitacre** [comment]
I think it's mostly for dev? Is that useful to us? 🤔

https://astro.build/blog/sentry-official-monitoring-partner/

**Comment by vladh** [comment]
If someone is using it, by all means let's leave it in. If nobody is using it yet, let's add it back later IMO!

**Comment by chadwhitacre** [comment]
One way to find out. 🙃

**Pull request merged**
